### PR TITLE
Fix issue with backslashes in strings key

### PR DESCRIPTION
**Pull request by dtygel**
Marcel, after you've refactored from .js to .json, backslashes are not accepted anymore in strings' keys. I've corrected this in en_EN and pt_BR in this commit.

### CODE REVIEW

**Comment by MTRNord** [comment]
@dtygel 2 things about it. 1. I am moving the json File to riot because of the New loading type 2. Backslashes for Single quotes are not needed in Json and escaping them Breaks Json. But on the otherhand weblate doesn't like Single quotes somehow. So please delay this PR/ Move it to the riot-web repo.

**Comment by dtygel** [comment]
@MTRNord 

1. Was this decision of moving the strings of matrix-react-sdk to riot-web taken in dialog with riot core developpers? It seems to me a little weird to have both matrix-react-sdk and riot-web in the same place. This would somehow make both packages absolutely inter-dependent, and then we could not consider "matrix-react-sdk" as an independent library anymore. Was it discussed?
1. Ok to delay the PR. Please let me know then how to move the strings to riot.

**Comment by MTRNord** [comment]
@dtygel point 1. is a webpack "issue" I can't get the unbundeled files from react-sdk into riot-web. Thats seems like it is a design "issue" of webpack. THe new way does only download the needed json file if the user changes the language and does not bundle it with webpack. Advatage is to get a smaller riot. I know it is not optimal but I did not find another way as react-sdk is always bundeled

2. It will be as simple as to copy and paste I guess.

**Comment by MTRNord** [comment]
@dtygel or if this PR is ready to push I will merge it first so point 2 is resolving itself as I am the one moving them.

**Comment by MTRNord** [comment]
@dtygel ok nevermind there is no file moving required I just found out as I can copy them over at build time and than merge these files.

**Comment by MTRNord** [comment]
Is this PR ready to push? @dtygel

**Comment by dtygel** [comment]
Yes!

**Pull request merged**
